valve_parse_sources = files(
  'tu/accepts_numeric_value_.c',
  'tu/action_.c',
  'tu/array_element_.c',
  'tu/array_value_.c',
  'tu/assign_value_.c',
  'tu/bool_value_.c',
  'tu/check_int_bounds_.c',
  'tu/command_.c',
  'tu/consumable_next_value_.c',
  'tu/dispatch_reserved_.c',
  'tu/dispatch_reserved_target_.c',
  'tu/double_literal_.c',
  'tu/effective_scalar_value_.c',
  'tu/enable_disable_.c',
  'tu/extract_reserved_target_.c',
  'tu/finish_.c',
  'tu/has_style_.c',
  'tu/int_literal_.c',
  'tu/is_enable_disable_.c',
  'tu/kv_value_.c',
  'tu/long_option_.c',
  'tu/looks_like_negative_number_.c',
  'tu/looks_like_option_.c',
  'tu/option_name_in_token_.c',
  'tu/options_.c',
  'tu/parse.c',
  'tu/reserved_token_.c',
  'tu/scalar_value_.c',
  'tu/select_subverb_.c',
  'tu/select_verb_.c',
  'tu/short_option_.c',
  'tu/token_has_double_mark_.c',
  'tu/try_reserved_.c',
  'tu/unknown_help_message_.c',
  'tu/user_has_option_for_token_.c',
)
