core_c_args = ['-DVALVE_VERSION="' + valve_version + '"']
if host_machine.system() == 'linux'
  core_c_args += '-D_GNU_SOURCE'
endif

core_sources = files(
  'unit/argv/destroy.c',
  'unit/color.c',
  'unit/conflict/other_.c',
  'unit/conflict/seen_.c',
  'unit/conflict/vl_conflict_active_.c',
  'unit/conflict/vl_conflict_add_.c',
  'unit/conflict/vl_conflict_error_.c',
  'unit/conflict/vl_conflict_exists_.c',
  'unit/conflict/vl_conflicts_check_.c',
  'unit/conflict/vl_conflicts_clear_.c',
  'unit/conflict/vl_conflicts_copy_.c',
  'unit/conflict/vl_conflicts_copy_table_.c',
  'unit/error_add_.c',
  'unit/error_at.c',
  'unit/error_count.c',
  'unit/errors_foreach.c',
  'unit/errors_print.c',
  'unit/find_option_.c',
  'unit/help_print_.c',
  'unit/help_resolve.c',
  'unit/help_resolve_internal_.c',
  'unit/help_target.c',
  'unit/option/annotations_print_.c',
  'unit/option/array_free_.c',
  'unit/option/collides_with_globals_.c',
  'unit/option/conflict_count_.c',
  'unit/option/conflicts_valid_.c',
  'unit/option/duration_parse_.c',
  'unit/option/have_duplicate_long_.c',
  'unit/option/have_duplicate_short_.c',
  'unit/option/in_.c',
  'unit/option/label_.c',
  'unit/option/label_print_.c',
  'unit/option/mapped_.c',
  'unit/option/option_count_.c',
  'unit/option/option_name_valid_.c',
  'unit/option/options_copy_.c',
  'unit/option/options_have_invalid_.c',
  'unit/option/options_use_reserved_.c',
  'unit/option/repeat_valid_.c',
  'unit/option/requirement_count_.c',
  'unit/option/requirements_valid_.c',
  'unit/option/type_valid_.c',
  'unit/option/usage_print_.c',
  'unit/option/value_label_.c',
  'unit/option/value_valid_.c',
  'unit/option/visible_.c',
  'unit/parse.c',
  'unit/path_split.c',
  'unit/required_check_.c',
  'unit/requirement/forward_seen_.c',
  'unit/requirement/reverse_seen_.c',
  'unit/requirement/vl_requirement_active_.c',
  'unit/requirement/vl_requirement_add_.c',
  'unit/requirement/vl_requirement_error_.c',
  'unit/requirement/vl_requirement_exists_.c',
  'unit/requirement/vl_requirements_check_.c',
  'unit/requirement/vl_requirements_clear_.c',
  'unit/requirement/vl_requirements_copy_.c',
  'unit/requirement/vl_requirements_copy_table_.c',
  'unit/reserved.c',
  'unit/reserved_fired.c',
  'unit/result/at.c',
  'unit/result/count.c',
  'unit/result/find_.c',
  'unit/result/set_.c',
  'unit/result/vl_results_clear_.c',
  'unit/schema/validate_.c',
  'unit/targets_clear.c',
  'unit/value/clear.c',
  'unit/value/has.c',
  'unit/value/vl_get.c',
  'unit/valve.c',
  'unit/valve_print_.c',
  'unit/verb/have_duplicate_.c',
  'unit/verb/subverb_get.c',
  'unit/verb/table_count_.c',
  'unit/verb/verb_array_clear_.c',
  'unit/verb/verb_copy_one_.c',
  'unit/verb/verb_count_.c',
  'unit/verb/verb_name_valid_.c',
  'unit/verb/verbs_have_invalid_.c',
  'unit/verb/verbs_use_reserved_.c',
  'unit/verb/vl_verb_get.c',
  'unit/version_get.c',
  'unit/version_print_.c',
  'unit/version_string.c',
  'unit/vl_options_clear_.c',
)

core_version = valve_version

valve_lib = library(
  'valve',
  core_sources,
  include_directories: inc,
  c_args: core_c_args,
  install: true,
  version: core_version.split('-')[0],
  soversion: '0',
)

valve_dep = declare_dependency(
  include_directories: inc,
  link_with: valve_lib,
)

pkg = import('pkgconfig')
pkg.generate(
  name: 'valve',
  description: 'CLI args parsing library',
  version: core_version,
  libraries: valve_lib,
  subdirs: '',
)
