valve_c_args = ['-DVALVE_VERSION="' + valve_version + '"']
if host_machine.system() == 'linux'
  valve_c_args += '-D_GNU_SOURCE'
endif

valve_sources = files(
  'valve/tu/action/action_count_.c',
  'valve/tu/action/actions_valid_.c',
  'valve/tu/action/vl_action_find_.c',
  'valve/tu/action/vl_action_fired.c',
  'valve/tu/action/vl_actions_clear_.c',
  'valve/tu/action/vl_actions_copy_.c',
  'valve/tu/argv/destroy.c',
  'valve/tu/color.c',
  'valve/tu/conflict/other_.c',
  'valve/tu/conflict/seen_.c',
  'valve/tu/conflict/vl_conflict_active_.c',
  'valve/tu/conflict/vl_conflict_add_.c',
  'valve/tu/conflict/vl_conflict_error_.c',
  'valve/tu/conflict/vl_conflict_exists_.c',
  'valve/tu/conflict/vl_conflicts_check_.c',
  'valve/tu/conflict/vl_conflicts_clear_.c',
  'valve/tu/conflict/vl_conflicts_copy_.c',
  'valve/tu/conflict/vl_conflicts_copy_table_.c',
  'valve/tu/error_add_.c',
  'valve/tu/error_at.c',
  'valve/tu/error_count.c',
  'valve/tu/errors_foreach.c',
  'valve/tu/errors_print.c',
  'valve/tu/find_option_.c',
  'valve/tu/help_print_.c',
  'valve/tu/help_resolve.c',
  'valve/tu/help_resolve_internal_.c',
  'valve/tu/help_target.c',
  'valve/tu/option/annotations_print_.c',
  'valve/tu/option/array_free_.c',
  'valve/tu/option/c_locale_.c',
  'valve/tu/option/collides_with_globals_.c',
  'valve/tu/option/command_valid_.c',
  'valve/tu/option/conflict_count_.c',
  'valve/tu/option/conflicts_valid_.c',
  'valve/tu/option/duration_parse_.c',
  'valve/tu/option/find_command_.c',
  'valve/tu/option/have_duplicate_long_.c',
  'valve/tu/option/have_duplicate_short_.c',
  'valve/tu/option/in_.c',
  'valve/tu/option/kv_parse_.c',
  'valve/tu/option/label_.c',
  'valve/tu/option/label_print_.c',
  'valve/tu/option/mapped_.c',
  'valve/tu/option/option_count_.c',
  'valve/tu/option/option_name_valid_.c',
  'valve/tu/option/options_command_count_.c',
  'valve/tu/option/options_copy_.c',
  'valve/tu/option/options_have_invalid_.c',
  'valve/tu/option/options_use_reserved_.c',
  'valve/tu/option/repeat_valid_.c',
  'valve/tu/option/requirement_count_.c',
  'valve/tu/option/requirements_valid_.c',
  'valve/tu/option/scalar_auto_.c',
  'valve/tu/option/strtod_c_.c',
  'valve/tu/option/type_valid_.c',
  'valve/tu/option/usage_print_.c',
  'valve/tu/option/value_label_.c',
  'valve/tu/option/value_valid_.c',
  'valve/tu/option/visible_.c',
  'valve/tu/parse.c',
  'valve/tu/parse_command_.c',
  'valve/tu/path_split.c',
  'valve/tu/required_check_.c',
  'valve/tu/requirement/forward_seen_.c',
  'valve/tu/requirement/reverse_seen_.c',
  'valve/tu/requirement/vl_requirement_active_.c',
  'valve/tu/requirement/vl_requirement_add_.c',
  'valve/tu/requirement/vl_requirement_error_.c',
  'valve/tu/requirement/vl_requirement_exists_.c',
  'valve/tu/requirement/vl_requirements_check_.c',
  'valve/tu/requirement/vl_requirements_clear_.c',
  'valve/tu/requirement/vl_requirements_copy_.c',
  'valve/tu/requirement/vl_requirements_copy_table_.c',
  'valve/tu/reserved.c',
  'valve/tu/reserved_fired.c',
  'valve/tu/result/at.c',
  'valve/tu/result/count.c',
  'valve/tu/result/find_.c',
  'valve/tu/result/set_.c',
  'valve/tu/result/vl_results_clear_.c',
  'valve/tu/schema/validate_.c',
  'valve/tu/targets_clear.c',
  'valve/tu/value/clear.c',
  'valve/tu/value/has.c',
  'valve/tu/value/vl_get.c',
  'valve/tu/valve.c',
  'valve/tu/valve_print_.c',
  'valve/tu/verb/have_duplicate_.c',
  'valve/tu/verb/subverb_get.c',
  'valve/tu/verb/table_count_.c',
  'valve/tu/verb/verb_array_clear_.c',
  'valve/tu/verb/verb_copy_one_.c',
  'valve/tu/verb/verb_count_.c',
  'valve/tu/verb/verb_name_valid_.c',
  'valve/tu/verb/verbs_have_invalid_.c',
  'valve/tu/verb/verbs_use_reserved_.c',
  'valve/tu/verb/vl_verb_get.c',
  'valve/tu/version_get.c',
  'valve/tu/version_print_.c',
  'valve/tu/version_string.c',
  'valve/tu/vl_options_clear_.c',
)

valve_lib = library(
  'valve',
  valve_sources,
  include_directories: inc,
  c_args: valve_c_args,
  install: true,
  version: valve_version.split('-')[0],
  soversion: '0',
)

valve_dep = declare_dependency(
  include_directories: inc,
  link_with: valve_lib,
)

pkg = import('pkgconfig')
pkg.generate(
  name: 'valve',
  description: 'CLI args parsing library',
  version: valve_version,
  libraries: valve_lib,
  subdirs: '',
)
